version: '3.9'

services:
  api1:
    build: .
    ports: 
      - 8080
  api2:
    build: .
    ports: 
      - 8080
  api3:
    build: .
    ports: 
      - 8080
  api4:
    build: .
    ports: 
      - 8080
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf #copy the conf file to the Nginx container
    ports:
      - 80:80 #map local host port 80 to port 80 within the Nginx container
