version: '3.9'

services:
  api1:
    build: .
    ports: 
      - 8080
  api2:
    build: .
    ports: 
      - 8080
  api3:
    build: .
    ports: 
      - 8080
  api4:
    build: .
    ports: 
      - 8080
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
